#ifndef WEBCAMCAPPRIMITIVES_GLOBAL_H
#define WEBCAMCAPPRIMITIVES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBCAMCAPPRIMITIVES_LIBRARY)
#  define WEBCAMCAPPRIMITIVESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBCAMCAPPRIMITIVESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBCAMCAPPRIMITIVES_GLOBAL_H
