#ifndef WEBCAMCAPGUI_GLOBAL_H
#define WEBCAMCAPGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBCAMCAPGUI_LIBRARY)
#  define WEBCAMCAPGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBCAMCAPGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBCAMCAPGUI_GLOBAL_H
