#ifndef WEBCAMCAPINTERFACES_GLOBAL_H
#define WEBCAMCAPINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBCAMCAPINTERFACES_LIBRARY)
#  define WEBCAMCAPINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBCAMCAPINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBCAMCAPINTERFACES_GLOBAL_H
